# Dependencies
markdown: kramdown
highlighter: Rouge
encoding: UTF-8 

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Senan's Blog
description:      'A technical blog documenting my personal and academic pursuits.'
url:              https://github.com/SenanS/
baseurl:          /

plugins: 
  - jekyll-paginate
  - jekyll-toc

author:
  name:           'Senan Stanley'

paginate:         3

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/SenanS/Technical-Blog
